name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - run: pnpm run build
      - run: git config --global user.name "bengaudry"
      - run: git config --global user.email "bengaudry@outlook.fr"
      - run: pnpm run deploy
